library(mapview)
library(mapedit)
library(raster)
r = raster("data/cci_lc_australia.tif")
my_map = mapview(r)
my_points = mapedit::drawFeatures(my_map)
# plot(r)
# plot(st_geometry(my_points), add = TRUE)
st_write(my_points, "data/sample_points.gpkg")
